import { Listing } from "./types";

export const listings: Listing[] = [
  {
    id: "l1",
    title: "Clean, dry garage — 15 min from city center",
    description:
      "Single-car garage, rarely used. Easy street access for drop-off. Good for furniture, boxes, or seasonal items.",
    spaceType: "garage",
    category: "personal",
    city: "Lahore",
    neighborhood: "Gulberg",
    sizeSqFt: 180,
    pricePerMonth: 45,
    currency: "USD",
    images: [],
    amenities: ["24/7 access", "CCTV", "Ground floor"],
    host: {
      id: "h1",
      name: "Hamza R.",
      verified: true,
      responseRate: 96,
      memberSince: "2025-02-01",
    },
    availableFrom: "2026-09-01",
    minDurationMonths: 1,
    rating: 4.8,
    reviewCount: 23,
  },
  {
    id: "l2",
    title: "Spare storeroom for e-commerce inventory",
    description:
      "Ground-floor storeroom attached to a shop. Ideal for online sellers who need overflow inventory space near a delivery route.",
    spaceType: "office",
    category: "business",
    city: "Lahore",
    neighborhood: "Johar Town",
    sizeSqFt: 320,
    pricePerMonth: 90,
    currency: "USD",
    images: [],
    amenities: ["Shelving included", "Loading access", "Daytime staff on site"],
    host: {
      id: "h2",
      name: "Sana K.",
      verified: true,
      responseRate: 100,
      memberSince: "2024-11-12",
    },
    availableFrom: "2026-08-15",
    minDurationMonths: 3,
    rating: 4.9,
    reviewCount: 41,
  },
  {
    id: "l3",
    title: "Basement room, climate-stable",
    description:
      "Dry basement room in a residential home. Stays cool year-round — good for anything sensitive to heat.",
    spaceType: "basement",
    category: "personal",
    city: "Karachi",
    neighborhood: "DHA Phase 5",
    sizeSqFt: 140,
    pricePerMonth: 38,
    currency: "USD",
    images: [],
    amenities: ["Climate stable", "Private entrance"],
    host: {
      id: "h3",
      name: "Bilal M.",
      verified: false,
      responseRate: 82,
      memberSince: "2026-01-20",
    },
    availableFrom: "2026-09-10",
    minDurationMonths: 2,
    rating: 4.5,
    reviewCount: 9,
  },
  {
    id: "l4",
    title: "Small shed, ideal for tools & seasonal gear",
    description: "Compact backyard shed. Best for bikes, tools, camping or seasonal equipment.",
    spaceType: "shed",
    category: "personal",
    city: "Islamabad",
    neighborhood: "F-10",
    sizeSqFt: 60,
    pricePerMonth: 20,
    currency: "USD",
    images: [],
    amenities: ["Padlock provided"],
    host: {
      id: "h4",
      name: "Ayesha T.",
      verified: true,
      responseRate: 91,
      memberSince: "2025-06-05",
    },
    availableFrom: "2026-08-20",
    minDurationMonths: 1,
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: "l5",
    title: "Unused office room — good for pallets",
    description:
      "Empty office room in a small commercial plaza, unused evenings and weekends. Freight elevator access.",
    spaceType: "warehouse",
    category: "business",
    city: "Lahore",
    neighborhood: "DHA Phase 6",
    sizeSqFt: 500,
    pricePerMonth: 150,
    currency: "USD",
    images: [],
    amenities: ["Freight elevator", "24/7 access", "CCTV"],
    host: {
      id: "h5",
      name: "Usman F.",
      verified: true,
      responseRate: 98,
      memberSince: "2024-09-18",
    },
    availableFrom: "2026-09-05",
    minDurationMonths: 3,
    rating: 4.6,
    reviewCount: 12,
  },
  {
    id: "l6",
    title: "Guest room, occasional use only",
    description: "Furnished guest room used maybe twice a year. Suitable for boxes and small furniture.",
    spaceType: "room",
    category: "personal",
    city: "Karachi",
    neighborhood: "Clifton",
    sizeSqFt: 110,
    pricePerMonth: 35,
    currency: "USD",
    images: [],
    amenities: ["Carpeted", "Ground floor"],
    host: {
      id: "h6",
      name: "Mariam S.",
      verified: false,
      responseRate: 75,
      memberSince: "2026-03-11",
    },
    availableFrom: "2026-10-01",
    minDurationMonths: 1,
    rating: 4.3,
    reviewCount: 6,
  },
];

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}
